name: spark-substrait-gateway-env
channels:
  - conda-forge
dependencies:
  - pip
  - pre-commit
  - protobuf >= 4.21.6
  - grpcio >= 1.48.1
  - grpcio-tools
  - pytest >= 7.0.0
  - python >= 3.8.1
  - setuptools >= 61.0.0
  - setuptools_scm >= 6.2.0
  - python-substrait
  - mypy-protobuf
  - types-protobuf
  - pip:
    - adbc_driver_manager
    - pyarrow
    - duckdb
    - datafusion
    - pyspark
    - substrait-validator
