name: spark-substrait-gateway-env
channels:
  - conda-forge
dependencies:
  - buf
  - pip
  - pre-commit
  - protobuf = 3.20.1  # protobuf==3.20 C extensions aren't compatible with 3.19.4
  - protoletariat >= 2.0.0
  - pytest >= 7.0.0
  - python >= 3.8.1
  - setuptools >= 61.0.0
  - setuptools_scm >= 6.2.0
