name: spark-substrait-gateway-env
channels:
  - conda-forge
dependencies:
  - pip
  - pre-commit
  - grpcio >= 1.48.1
  - grpcio-status
  - grpcio-tools
  - pytest >= 8.0.0
  - setuptools >= 61.0.0
  - setuptools_scm >= 6.2.0
  - mypy-protobuf
  - types-protobuf >= 4.25.0, < 5.0.0
  - numpy < 2.0.0
  - ibis-substrait == 4.0.*
  - Faker
  - pip:
    - adbc_driver_manager
    - cargo
    - pyarrow >= 17.0.0
    - pyarrow-hotfix
    - duckdb == 1.1.0
    - datafusion == 41.0.*
    - grpcio-channelz
    - pyspark
    - pandas >= 1.0.5
    - pyhamcrest
    - substrait == 0.21.0
    - substrait-validator
    - pytest-timeout
    - protobuf >= 4.25.3, < 5.0.0
    - cryptography == 43.0.*
    - click == 8.1.*
    - pyjwt == 2.8.*

