name: spark-substrait-gateway-env
channels:
  - conda-forge
dependencies:
  - pip
  - pre-commit
  - protobuf >= 4.21.6, < 5.0.0
  - grpcio >= 1.48.1
  - grpcio-status
  - grpcio-tools
  - pytest >= 8.0.0
  - setuptools >= 61.0.0
  - setuptools_scm >= 6.2.0
  - python-substrait >= 0.14.1
  - mypy-protobuf
  - types-protobuf
  - Faker
  - pip:
    - adbc_driver_manager
    - cargo
    - pyarrow >= 16.0.0
    - duckdb >= 1.0.0
    - datafusion >= 36.0.0
    - pyspark
    - pandas >= 1.0.5
    - pyhamcrest
    - substrait-validator
    - pytest-timeout
